package graphics;

public enum Tile {
	GRASS,GRASS1,GRASS2,GRASS3,TREE1,TREE2,TREE3,
	HOUSE1,HOUSE2,HOUSE3,MOUNTAIN1,MOUNTAIN2,MOUNTAIN3,HILL,
	FARM1,FARM2,FARM3,FARM4,LAKE,LAKE1,LAK2,
	FAR5,TOWER,TOWERR,TOWERG,TOWERB,TOWERY,SMALLHILLS,
	BROKENTOWER,GATE,GATER,GATEG,GATEB,GATEY,KEEP,
	Z1,Z2,Z3,Z4,Z5,Z6,Z7,
	HUT1,HUT2,Z8,Z9,Z10,Z11,FIELD

}
